### ISSUE TITLE
Can I use the VSTS Bot to add work items to the backlog?

### ISSUE THREAD

**Issue by LordScree** [ALM-Rangers/VSTS-Bot#152]
Hi, is it possible to use the VSTS Bot to add work items to the backlog, via Slack. For example:

/vsts-bot add "something" 

?

**Comment by almguru** [comment]
Hi Oliver,

No, it’s not possible.

~vg

Sent from from iPhone
Typos introduced for authenticity

2 сент. 2018 г., в 15:38, Oliver Clare <notifications@github.com<mailto:notifications@github.com>> написал(а):


Hi, is it possible to use the VSTS Bot to add work items to the backlog, via Slack. For example:

/vsts-bot add "something"

?

**Comment by LordScree** [comment]
Okay, thanks.
