### ISSUE TITLE
Awesome Unit Testing Package

### ISSUE THREAD

**Issue by garfbradaz** [ALM-Rangers/VSTS-Bot#89]
Hey Guys,

I was pointed in this direction from here to look at your implementation of mocking out the Bot Framework:

https://channel9.msdn.com/Series/DevOps-for-the-Bot-Framework/Testing-the-Bot-Framework

Have you released any generalized nuget package for this? Given me some good ideas on where to start now so thank you!

**Comment by jeffrey-opdam** [comment]
Hi Gareth,

Thank you for your kind words. What would you like to see in the nuget package? We actually have thought about it.

**Comment by jeffrey-opdam** [comment]
Hi,

I am closing this issue. If you are still interested, we can reopen it again.
