### ISSUE TITLE
VSTS Bot responses twice every one message. and it doesn't work as expected.

### ISSUE THREAD

**Issue by mayuki** [ALM-Rangers/VSTS-Bot#91]
VSTS Bot responses twice every one message. and it doesn't work as expected.

![image](https://user-images.githubusercontent.com/9012/31535547-6f3c3072-b036-11e7-8bab-2b03fdaad617.png)

## Example responses
- **Me**: connect
- **VSTS-Bot**: Please select an account to connect to. (snip)
- **VSTS-Bot**: Please login to Visual Studio Services. After login you will receive a five digit pin ...(snip)
- **VSTS-Bot**: Sorry, I do not recognize the provided pin. Please try again.
- **Me**: help
- **VSTS-Bot**: I am here to help you. Please select one of the following commands. (snip)
- **VSTS-Bot**: I am here to help you. Please select one of the following commands. (snip)

**Comment by jeffrey-opdam** [comment]
Hi Mayuki,

Thank you for reporting this to us.

Could you please reset your profile by typing ' /deleteprofile' (do not forget the space before the slash).

Do you have a start and end date for me with timezone, so we can check the logs.

**Comment by mayuki** [comment]
I reset my profile by above command. After then reconnect VSTS Bot, it seems to work fine. 👍
My timezone setting is 'Japan Standard Time (+09:00)'.

- Add the bot app to Slack team: 10/13/2017 16:30+09:00; 10/13/2017 07:30 (UTC)
- Reset my profile: 10/13/2017 17:16+09:00; 10/13/2017 08:16 (UTC)

**Comment by jeffrey-opdam** [comment]
Tnx,

Good to hear, the reset worked. I will get back to you asap, when i read through the logs.

**Comment by jeffrey-opdam** [comment]
Btw, we would appreciate any feedback you have.

**Comment by jeffrey-opdam** [comment]
Investigating the logs helped us understand the issue better. We made a little change that will prevent duplicated messages from Slack. We will also report this issue with the Bot Framework team.

**Comment by mayuki** [comment]
Thank you for investigating and fixing! I appreciate quick response.

**Comment by jeffrey-opdam** [comment]
[Issue reported with the Bot Framework team](https://github.com/Microsoft/BotBuilder/issues/3614)
