### ISSUE TITLE
Slack Email doesn't match my VSTS account login - Unable to verify PIN

### ISSUE THREAD

**Issue by smaglio81** [ALM-Rangers/VSTS-Bot#93]
Hello,

I am trying to add the bot through Slack, and I forgot that my slack email is not by VSTS account email (I'm not sure how everything is associated).

![image](https://user-images.githubusercontent.com/169953/31566114-1a3520b0-b01e-11e7-9ad9-249a750e5501.png)

So,

- I hit connect the first time with the wrong email address
- Realizing the mistake I changed my email address in slack and hit connect again
- I signed out and signed back into VSTS (actually using a third email address)
- VSTS asked me to confirm the bot and then presented the pin
- The bot did accept the and asked if I wanted to join my VSTS account (sist-sa-ucsb)
- But, I can't run any commands with getting the 'Sorry, I do not recognize the provided pin. Please try again.' message

I then read on of the other issues, and tried ' /deleteprofile'

This time with the correct email (I think), I went back through the Connect step, but VSTS isn't giving me a new PIN. And I keep getting the 'Sorry, I do not recognize the provided pin. Please try again.' message.

Do you have any suggestions?

Thanks

**Comment by jeffrey-opdam** [comment]
Hi,

First thank you for using the bot. Could you start with the command ' /deleteprofile', make sure you have a space before the dash. Then type 'connect' again. Click on the auth required link, which will open up your browser with the accept page. Click on 'accept' (which is at the bottom of the page) and you will be redirected to the bot pin page. Copy the pin number and go back to slack. Paste the pin number where into the conversation with the bot. From there you will be asked to choose your account and team project

**Comment by smaglio81** [comment]
Thank You. BTW, is there a way to select multiple projects?

The last time around, I didn't click on the 'Authentication is required' link. I'll leave feedback as I start to use it more. Thanks for putting it together.

BTW, at the moment, the buttons in the messages aren't working. Typing in the name I want worked fine though.

![image](https://user-images.githubusercontent.com/169953/31580924-15b83a28-b112-11e7-8978-6f0f564bc8e8.png)

**Comment by jeffrey-opdam** [comment]
Hi Steven,

You can switch projects by typing 'connect' again.

**Comment by jeffrey-opdam** [comment]
The buttons are working again. Thank you for reporting.

If you have ideas, feature request or issues, let us know, we will take care of them asap.

Or you can help us out by submitting a Pull Request.
