### ISSUE TITLE
Invalid URI: The hostname could not be parsed error when connecting VSTS-Bot in Slack

### ISSUE THREAD

**Issue by tlentine** [ALM-Rangers/VSTS-Bot#98]
This is somewhat similar to the issue reported here: https://github.com/ALM-Rangers/VSTS-Bot/issues/93

I tried to connect the VSTS-Bot in Slack to VSTS and initially it seemed like it worked. Then I started getting errors to the "effect that my user account was not authorized to access this resource." I am the owner of the account, so this isn't a valid response as I do have permission to view Builds and Releases.

I tried the /deleteprofile option as suggested in the other issue, but now when I try to connect I get a series of errors as seen in the attached screenshot.

I've tried removing the bot from Slack, revoking permission in VSTS for the bot and starting over, but that doesn't seem to have helped at all.

Is there anything else I can try to get this connected and working?

![vsts-bot-error](https://user-images.githubusercontent.com/14112283/31827705-61f4c320-b586-11e7-9d39-b6a6bfba2261.png)

**Comment by jeffrey-opdam** [comment]
Hi @tlentine,

Thank you for trying out the bot and reporting your issue to us. 

First:
Can you change the command from 'connect /deleteprofile' to ' /deleteprofile'. Make sure you have a space before the slash. ' /deleteprofile' is it's own command.

Second, Issue with the authorization:
Can you make sure, when you go to the accept page, that you have selected the correct account, by reviewing the account after the text 'App requests the following permissions from:' like ' your@email.address (**Microsoft account**)'. It might be the case that you have connected your account with another Azure Active Directory Account and/or another Microsoft Account.

Copy the url and click on your name on the top right corner of the page, which will redirect you to your profile page. There you have an option to select another Microsoft Account or a Azure Active Directory, just bellow your email address on the left side of the page.

Hopefully this resolves your issue. If not, please let us know and we will help you further.

**Comment by tlentine** [comment]
Thanks, I was misinterpreting the /deleteprofile  command. I was able to delete the profile and start over. 
The Microsoft Account I am connecting with has access to multiple Team Service Accounts. 

When authenticating (connect command, log into VSTS, enter pin) the Response is "Please select an account to connect to" but it doesn't list anything. I typed the team name and was prompted to login again, (which I did) and after entering the pin I see the list of projects. I selected the one I am interested in connecting and received the response that the bot is now connected to the team project.

At this point I can enter either Builds and Releases and see the options that are available in our project. However, if I enter Approvals I get the exception that I am not authorized to access the resource (which doesn't really make sense to me given the account I've logged in with owns the account.

I also have an organizational account (Azure AD based) that has access to the team. For giggles, I deleted the profile and this time connected with the Azure AD based account. I am able to connect, but attempting to list Approvals fails as well.

So, deleting the profile and starting over solves the reported issue, but there's something going on with Approvals that I will try to sort out next week as time permits - it could be a permission issue on our side (though with the MSA account I don't think this would explain the error).

Thanks for your help!

**Comment by jeffrey-opdam** [comment]
Just let us know, then we will pick it up when you are ready.
